# Generated by Django 4.2.17 on 2024-12-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruckModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('applicant', models.CharField(default=None, max_length=255, null=True)),
                ('facility_type', models.CharField(default=None, max_length=50, null=True)),
                ('cnn', models.BigIntegerField()),
                ('location_description', models.TextField(default=None, null=True)),
                ('address', models.TextField(default=None, null=True)),
                ('blocklot', models.CharField(default=None, max_length=32, null=True)),
                ('block', models.CharField(default=None, max_length=32, null=True)),
                ('lot', models.CharField(default=None, max_length=32, null=True)),
                ('permit', models.CharField(default=None, max_length=64, null=True)),
                ('status', models.CharField(default=None, max_length=64, null=True)),
                ('food_items', models.TextField(blank=True, default=None, null=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('schedule_url', models.URLField()),
                ('days_hours', models.CharField(default=None, max_length=255, null=True)),
                ('noi_sent', models.CharField(default=None, max_length=64, null=True)),
                ('received', models.IntegerField(blank=True, null=True)),
                ('prior_permit', models.BooleanField()),
                ('location', models.CharField(default=None, max_length=255, null=True)),
                ('fire_prevention_districts', models.IntegerField()),
                ('police_districts', models.IntegerField()),
                ('supervisor_districts', models.IntegerField()),
                ('zip_codes', models.IntegerField()),
                ('neighborhoods_old', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
